version: '3.8'

services:
  spike-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spike-tracker-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - spike-tracker-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: ["java", "-jar", "app.jar"]

networks:
  spike-tracker-network:
    driver: bridge