global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spiketracker'
    static_configs:
      - targets: ['spike-tracker:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s